apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
  labels:
    io.kompose.service: dataprep-02
  name: dataprep-02
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  ports:
    - name: "6007"
      port: 6007
      targetPort: 6007
  selector:
    io.kompose.service: dataprep-02
