---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retriever-megaservice-route
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  host: megaservice-{{ .Values.global.amdllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
  path: /v1/retrieval
  port:
    targetPort: 7000
  to:
    kind: Service
    name: retriever
    weight: 100
  wildcardPolicy: None
